{
  id: {timestamp},
  title: 'Dynamic playlist name',
    songs: [
  {
    "id": {timestamp},
    "title": "The Chainsmokers - Don't Let Me Down (Illenium Remix)",
    "duration": 219082,
    "stream_url": "https://api.soundcloudcom/tracks/250711755/stream",
    "uri": "https://api.soundcloud.com/tracks/250711755",
    "artwork_url": "https://i1.sndcdn.com/artworks-000150027827-4exjil-large.jpg"
  }]
}

[{
  "id": 159309722,
  "kind": "track",
  "created_at": "2014/07/18 22:19:36 +0000",
  "last_modified": "2017/02/23 10:00:33 +0000",
  "permalink": "houseofyogamix-1-1",
  "permalink_url": "https://soundcloud.com/karlak/houseofyogamix-1-1",
  "title": "HouseOfYogaMix(1.1)",
  "sharing": "public",
  "waveform_url": "https://w1.sndcdn.com/tXoNoctuY0TR_m.png",
  "stream_url": "",
  "uri": "https://api.soundcloud.com/tracks/159309722",
  "user_id": 1559138,
  "artwork_url": "https://i1.sndcdn.com/artworks-000085589499-5krasm-large.jpg",
  "comment_count": 66,
  "commentable": true,
  "description": "A mix of my favourite tracks collected the last few years of practicing and teaching house of yoga (a fusion of house/disco and yoga) www.housemusicyoga.com. All are tracks I've listened to again and again and again, as I've practiced house of yoga & so they are the ones that resonate most deeply with my own body and heart rhythms. Special thanks to the Travis Bickle Soundsystem for helping make it happen.\nDeepdiscohouse is the vibe! \n\nHope you enjoy, Karla x \nTracklist\nJust a Memory -6th Borough Project\nBad Desire - The Dead Rose Music Company\nWishing - Late Nite Tuff Guy\nDo for Love - Get Down Edits\nMy Woman (Wolf Mix)- Eddie C\nHarvest Moon - Poolside\nNice and Slow - Jessie Rose\nLost in Music - The Revenge \nOne Night in a Disco - LNTG\nHang Together - Keep Schtum\nThe Captain of Her Heart - Matrixmann's Shipwrecked Edit\nMove Me - LNTG\nMad World - Mojo Filter Cosmotronic Edit\n",
  "download_count": 100,
  "downloadable": false,
  "embeddable_by": "all",
  "favoritings_count": 0,
  "genre": "Deep Disco House Love",
  "isrc": "",
  "label_id": null,
  "label_name": "",
  "license": "all-rights-reserved",
  "original_content_size": 122218201,
  "original_format": "mp3",
  "playback_count": 59292,
  "purchase_title": null,
  "purchase_url": null,
  "release": "",
  "release_day": null,
  "release_month": null,
  "release_year": null,
  "reposts_count": 82,
  "state": "finished",
  "streamable": true,
  "tag_list": "House Disco Deep Love",
  "track_type": "",
  "user": {
    "avatar_url": "https://i1.sndcdn.com/avatars-000226918858-se63re-large.jpg",
    "id": 1559138,
    "kind": "user",
    "permalink_url": "http://soundcloud.com/karlak",
    "uri": "https://api.soundcloud.com/users/1559138",
    "username": "karlak",
    "permalink": "karlak",
    "last_modified": "2017/01/27 14:14:35 +0000"
  },
  "likes_count": 719,
  "attachments_uri": "https://api.soundcloud.com/tracks/159309722/attachments",
  "bpm": null,
  "key_signature": "",
  "user_favorite": false,
  "user_playback_count": null,
  "video_url": null,
  "download_url": null
}, {
  "id": 10791358,
  "kind": "track",
  "created_at": "2011/02/19 14:46:56 +0000",
  "last_modified": "2017/03/28 21:21:22 +0000",
  "permalink": "jennifer-lopez-ft-pitbull-on",
  "permalink_url": "https://soundcloud.com/ccw/jennifer-lopez-ft-pitbull-on",
  "title": "Jennifer Lopez ft. Pitbull - On The Floor (CCW Radio Edit) *Official* [Property Of Def Jam Records]",
  "duration": 222333,
  "sharing": "public",
  "waveform_url": "https://w1.sndcdn.com/r3XVGMvZb1vv_m.png",
  "stream_url": "https://api.soundcloud.com/tracks/10791358/stream",
  "uri": "https://api.soundcloud.com/tracks/10791358",
  "user_id": 1741058,
  "artwork_url": "https://i1.sndcdn.com/artworks-000004968966-07lwwq-large.jpg",
  "comment_count": 375,
  "commentable": true,
  "description": "(This OFFICIAL REMIX and all rights are the property of DEF JAM Records)\r\n(Promotional Use Only-Not For Sale or Distribution)\r\n\r\nClick \"Buy This Track\" to purchase on iTunes.",
  "download_count": 0,
  "downloadable": false,
  "embeddable_by": "all",
  "favoritings_count": 0,
  "genre": "Club House",
  "isrc": "",
  "label_id": null,
  "label_name": "Island/Def Jam",
  "license": "all-rights-reserved",
  "original_content_size": 3555161,
  "original_format": "mp3",
  "playback_count": 2741062,
  "purchase_title": null,
  "purchase_url": "http://itunes.apple.com/ca/album/on-floor-remixes-feat-pitbull/id419738361",
  "release": "",
  "release_day": 4,
  "release_month": 2,
  "release_year": 2011,
  "reposts_count": 3705,
  "state": "finished",
  "streamable": true,
  "tag_list": "On The Floor CCW Remix Mix Club Dance House Cajjmere Wray DJ Producer",
  "track_type": "remix",
  "user": {
    "avatar_url": "https://i1.sndcdn.com/avatars-000172968048-joulce-large.jpg",
    "id": 1741058,
    "kind": "user",
    "permalink_url": "http://soundcloud.com/ccw",
    "uri": "https://api.soundcloud.com/users/1741058",
    "username": "Cajjmere Wray",
    "permalink": "ccw",
    "last_modified": "2017/03/22 22:52:30 +0000"
  },
  "likes_count": 58283,
  "attachments_uri": "https://api.soundcloud.com/tracks/10791358/attachments",
  "bpm": null,
  "key_signature": "",
  "user_favorite": false,
  "user_playback_count": null,
  "video_url": null,
  "download_url": null
}, {
  "id": 148340824,
  "kind": "track",
  "created_at": "2014/05/07 12:34:47 +0000",
  "last_modified": "2017/02/20 09:27:29 +0000",
  "permalink": "charles-eddie-would-i-lie-to",
  "permalink_url": "https://soundcloud.com/maartenkarsen/charles-eddie-would-i-lie-to",
  "title": "Charles & Eddie - Would I Lie To You (Maklon Remix)",
  "duration": 222688,
  "sharing": "public",
  "waveform_url": "https://w1.sndcdn.com/5VEh1U9z6kd9_m.png",
  "stream_url": "https://api.soundcloud.com/tracks/148340824/stream",
  "uri": "https://api.soundcloud.com/tracks/148340824",
  "user_id": 5294273,
  "artwork_url": "https://i1.sndcdn.com/artworks-000078723378-gpz3db-large.jpg",
  "comment_count": 253,
  "commentable": true,
  "description": "A new re-edit remix of mine, enjoy!!\r\n",
  "download_count": 0,
  "downloadable": false,
  "embeddable_by": "all",
  "favoritings_count": 0,
  "genre": "Deep House",
  "isrc": "",
  "label_id": null,
  "label_name": "",
  "license": "all-rights-reserved",
  "original_content_size": 39266860,
  "original_format": "wav",
  "playback_count": 3457136,
  "purchase_title": "FREE DOWNLOAD!",
  "purchase_url": "https://www.facebook.com/OfficialMaklon/app_208195102528120",
  "release": "",
  "release_day": null,
  "release_month": null,
  "release_year": null,
  "reposts_count": 15599,
  "state": "finished",
  "streamable": true,
  "tag_list": "Deep House Remix 90's UKHouse",
  "track_type": "remix",
  "user": {
    "avatar_url": "https://i1.sndcdn.com/avatars-000090426997-buptpl-large.jpg",
    "id": 5294273,
    "kind": "user",
    "permalink_url": "http://soundcloud.com/maartenkarsen",
    "uri": "https://api.soundcloud.com/users/5294273",
    "username": "Maklon",
    "permalink": "maartenkarsen",
    "last_modified": "2017/01/12 11:50:07 +0000"
  },
  "likes_count": 90002,
  "attachments_uri": "https://api.soundcloud.com/tracks/148340824/attachments",
  "bpm": null,
  "key_signature": "",
  "user_favorite": false,
  "user_playback_count": null,
  "video_url": null,
  "download_url": null
}, {
  "id": 190643545,
  "kind": "track",
  "created_at": "2015/02/11 20:10:18 +0000",
  "last_modified": "2017/03/27 23:45:03 +0000",
  "permalink": "no-diggity",
  "permalink_url": "https://soundcloud.com/favulous/no-diggity",
  "title": "Favulous - No Diggity",
  "duration": 207482,
  "sharing": "public",
  "waveform_url": "https://w1.sndcdn.com/oJntOrG5ctlh_m.png",
  "stream_url": "https://api.soundcloud.com/tracks/190643545/stream",
  "uri": "https://api.soundcloud.com/tracks/190643545",
  "user_id": 4681114,
  "artwork_url": "https://i1.sndcdn.com/artworks-000106385269-nlhie0-large.jpg",
  "comment_count": 378,
  "commentable": true,
  "description": "This is my version of the 90's classic hit 'No Diggity' by Blackstreet: clean sound, crisp vocals, clever lyrics, great flow and song about girls with class and style, having some respect for 'em.\n\nFollow me on Instagram: @favulous",
  "download_count": 2004,
  "downloadable": false,
  "embeddable_by": "all",
  "favoritings_count": 0,
  "genre": "Favulous",
  "isrc": null,
  "label_id": null,
  "label_name": "",
  "license": "all-rights-reserved",
  "original_content_size": 8296615,
  "original_format": "mp3",
  "playback_count": 2378809,
  "purchase_title": "★ FREE DOWNLOAD ★",
  "purchase_url": "https://theartistunion.com/tracks/ccef77",
  "release": "",
  "release_day": 11,
  "release_month": 2,
  "release_year": 2015,
  "reposts_count": 14129,
  "state": "finished",
  "streamable": true,
  "tag_list": "\"Uk Bass\" \"Future Garage\" Bass Future Remix \"Deep House\" House Favulous Blackstreet \"No Diggity\" \"Future Sex\" \"Future House\"",
  "track_type": null,
  "user": {
    "avatar_url": "https://i1.sndcdn.com/avatars-000278997512-5c3euo-large.jpg",
    "id": 4681114,
    "kind": "user",
    "permalink_url": "http://soundcloud.com/favulous",
    "uri": "https://api.soundcloud.com/users/4681114",
    "username": "Favulous",
    "permalink": "favulous",
    "last_modified": "2017/02/07 20:13:26 +0000"
  },
  "likes_count": 78640,
  "attachments_uri": "https://api.soundcloud.com/tracks/190643545/attachments",
  "bpm": null,
  "key_signature": "",
  "user_favorite": false,
  "user_playback_count": null,
  "video_url": null,
  "download_url": null
}, {
  "id": 114294643,
  "kind": "track",
  "created_at": "2013/10/07 22:02:09 +0000",
  "last_modified": "2016/10/28 09:45:25 +0000",
  "permalink": "samira-said-mazal-official",
  "permalink_url": "https://soundcloud.com/ahmed-tawfiq-1/samira-said-mazal-official",
  "title": "SAMIRA SAID | MAZAL | OFFICIAL SONG | سميرة سعيد | مازال | النسخة الاصلية",
  "duration": 225379,
  "sharing": "public",
  "waveform_url": "https://w1.sndcdn.com/D69Ku10v2hEA_m.png",
  "stream_url": "https://api.soundcloud.com/tracks/114294643/stream",
  "uri": "https://api.soundcloud.com/tracks/114294643",
  "user_id": 38544917,
  "artwork_url": "https://i1.sndcdn.com/artworks-000059573852-q6wsyx-large.jpg",
  "comment_count": 413,
  "commentable": true,
  "description": "",
  "download_count": 0,
  "downloadable": false,
  "embeddable_by": "all",
  "favoritings_count": 0,
  "genre": "Samira said",
  "isrc": "",
  "label_id": null,
  "label_name": "",
  "license": "all-rights-reserved",
  "original_content_size": 3605473,
  "original_format": "mp3",
  "playback_count": 1708177,
  "purchase_title": null,
  "purchase_url": null,
  "release": "",
  "release_day": null,
  "release_month": null,
  "release_year": null,
  "reposts_count": 7455,
  "state": "finished",
  "streamable": true,
  "tag_list": "Trance House Single",
  "track_type": "",
  "user": {
    "avatar_url": "https://i1.sndcdn.com/avatars-000133240421-exyal5-large.jpg",
    "id": 38544917,
    "kind": "user",
    "permalink_url": "http://soundcloud.com/ahmed-tawfiq-1",
    "uri": "https://api.soundcloud.com/users/38544917",
    "username": "Ahmed Tawfiq ❼",
    "permalink": "ahmed-tawfiq-1",
    "last_modified": "2017/01/19 00:45:24 +0000"
  },
  "likes_count": 73192,
  "attachments_uri": "https://api.soundcloud.com/tracks/114294643/attachments",
  "bpm": null,
  "key_signature": "",
  "user_favorite": false,
  "user_playback_count": null,
  "video_url": null,
  "download_url": null
}, {
  "id": 143526638,
  "kind": "track",
  "created_at": "2014/04/07 14:56:51 +0000",
  "last_modified": "2017/02/24 13:41:29 +0000",
  "permalink": "marv-philipp-dittberner-wolke4",
  "permalink_url": "https://soundcloud.com/marv-music/marv-philipp-dittberner-wolke4",
  "title": "Philipp Dittberner & Marv - Wolke 4 (Original Mix)",
  "duration": 237945,
  "sharing": "public",
  "waveform_url": "https://w1.sndcdn.com/zVulyvOjeU3c_m.png",
  "stream_url": "https://api.soundcloud.com/tracks/143526638/stream",
  "uri": "https://api.soundcloud.com/tracks/143526638",
  "user_id": 32261864,
  "artwork_url": "https://i1.sndcdn.com/artworks-000075844798-rc0h26-large.jpg",
  "comment_count": 343,
  "commentable": true,
  "description": "I made another Track with https://soundcloud.com/philippdittberner!\nWe had a lot of fun creating this track. Hope you enjoy listening!\n\nBuy here\niTunes: http://goo.gl/gf9DwF\nAmazon: http://goo.gl/E82awN\nGooglePlay: http://goo.gl/Ev5oWx\n\nPicture from Cubagallery:\nhttp://www.cubagallery.co.nz/",
  "download_count": 2569,
  "downloadable": false,
  "embeddable_by": "all",
  "favoritings_count": 0,
  "genre": "Tech House/Acoustic",
  "isrc": "",
  "label_id": null,
  "label_name": "Sonnenkater",
  "license": "all-rights-reserved",
  "original_content_size": 42292986,
  "original_format": "wav",
  "playback_count": 2868191,
  "purchase_title": "Buy on iTunes",
  "purchase_url": "https://itunes.apple.com/de/album/wolke-4-single/id947919265",
  "release": "",
  "release_day": 16,
  "release_month": 1,
  "release_year": 2015,
  "reposts_count": 4158,
  "state": "finished",
  "streamable": true,
  "tag_list": "Philipp Dittberner Tech House Pop Singer Vocal Original Free Download Marv Deep Wolke 4",
  "track_type": "original",
  "user": {
    "avatar_url": "https://i1.sndcdn.com/avatars-000261440569-40alke-large.jpg",
    "id": 32261864,
    "kind": "user",
    "permalink_url": "http://soundcloud.com/marv-music",
    "uri": "https://api.soundcloud.com/users/32261864",
    "username": "Marv .",
    "permalink": "marv-music",
    "last_modified": "2016/12/13 09:09:43 +0000"
  },
  "likes_count": 41572,
  "attachments_uri": "https://api.soundcloud.com/tracks/143526638/attachments",
  "bpm": null,
  "key_signature": "",
  "user_favorite": false,
  "user_playback_count": null,
  "video_url": null,
  "download_url": null
}, {
  "id": 173674534,
  "kind": "track",
  "created_at": "2014/10/24 18:21:52 +0000",
  "last_modified": "2017/02/27 22:29:37 +0000",
  "permalink": "the-jackson-5-i-want-you-back-shaparder-lrx-remix",
  "permalink_url": "https://soundcloud.com/shaparder/the-jackson-5-i-want-you-back-shaparder-lrx-remix",
  "title": "The Jackson 5 - I Want You Back (Shaparder & LRX Remix)",
  "duration": 300513,
  "sharing": "public",
  "waveform_url": "https://w1.sndcdn.com/hxoBjPSIXeyH_m.png",
  "stream_url": "https://api.soundcloud.com/tracks/173674534/stream",
  "uri": "https://api.soundcloud.com/tracks/173674534",
  "user_id": 5671368,
  "artwork_url": "https://i1.sndcdn.com/artworks-000095001603-ziql2z-large.jpg",
  "comment_count": 612,
  "commentable": true,
  "description": "It's always a big thing to remix a track old as your grandmother, we put a lot of love in this one, it means a lot for us ! \n\nSigned to Universal Music.\n\nFollow us on Instagram for daily fun and music !\nSEE → instagram.com/shapardermusic\nFACEBOOK → https://www.facebook.com/Shaparder\n",
  "download_count": 0,
  "downloadable": false,
  "embeddable_by": "all",
  "favoritings_count": 0,
  "genre": "Jackson Summer",
  "isrc": "",
  "label_id": null,
  "label_name": "",
  "license": "cc-by-nc-nd",
  "original_content_size": 79493444,
  "original_format": "wav",
  "playback_count": 2659660,
  "purchase_title": "Free Download !",
  "purchase_url": "https://www.facebook.com/Shaparder/app_1377770235884432",
  "release": "",
  "release_day": null,
  "release_month": null,
  "release_year": null,
  "reposts_count": 11655,
  "state": "finished",
  "streamable": true,
  "tag_list": "Study Summer Chill \"Deep House\" \"Deep Bass\" \"Shaparder & LRX\" Shaparder Elerix \"Michael Jackson\" Hashtag \"Nice Music\" House Sun Sunny Party Bass \"Good Vibe\" \"Old Jackson\"",
  "track_type": "",
  "user": {
    "avatar_url": "https://i1.sndcdn.com/avatars-000185153966-fmbn9y-large.jpg",
    "id": 5671368,
    "kind": "user",
    "permalink_url": "http://soundcloud.com/shaparder",
    "uri": "https://api.soundcloud.com/users/5671368",
    "username": "Shaparder",
    "permalink": "shaparder",
    "last_modified": "2016/10/18 14:23:11 +0000"
  },
  "likes_count": 63917,
  "attachments_uri": "https://api.soundcloud.com/tracks/173674534/attachments",
  "bpm": null,
  "key_signature": "",
  "user_favorite": false,
  "user_playback_count": null,
  "video_url": null,
  "download_url": null
}, {
  "id": 134643370,
  "kind": "track",
  "created_at": "2014/02/13 19:36:34 +0000",
  "last_modified": "2017/03/28 01:55:41 +0000",
  "permalink": "lorde-team-elephante-remix",
  "permalink_url": "https://soundcloud.com/iamtheelephante/lorde-team-elephante-remix",
  "title": "Lorde - Team (Elephante Remix)",
  "duration": 240139,
  "sharing": "public",
  "waveform_url": "https://w1.sndcdn.com/WVVtwrfFH6SJ_m.png",
  "stream_url": "https://api.soundcloud.com/tracks/134643370/stream",
  "uri": "https://api.soundcloud.com/tracks/134643370",
  "user_id": 10915053,
  "artwork_url": "https://i1.sndcdn.com/artworks-000070762334-xuffcr-large.jpg",
  "comment_count": 813,
  "commentable": true,
  "description": "So one of my friends said this remix sounds like \"Elton John in the back of a limo driven by Big Bird\"... not really the reaction I was expecting, but I'll take it. I absolutely loved \"Team\" the first time I heard it, and after I still loved it after the 1000th time I heard it, I knew I had to remix it. Really proud of how this came out, even though it was one of the most frustrating remixes I've ever worked on - I almost smashed my computer a dozen times, and yelled at all my friends who told me that earlier versions sucked, even though they were right. So please, enjoy - and sorry neighbors for all the noise, I swear I'm not crazy, but no I won't turn it down.\n\nPS If we're being totally honest, I loved her performance at the Grammy's, seizures and everything.\n\nBooking & press inquiries: \nbooking@elephantemusic.com\n\nHaters, get at me:\nwww.twitter.com/IAmTheElephante\n\nLovers, go LIKE my page:\nwww.facebook.com/IAmTheElephante",
  "download_count": 0,
  "downloadable": false,
  "embeddable_by": "all",
  "favoritings_count": 0,
  "genre": "PHANTE",
  "isrc": null,
  "label_id": null,
  "label_name": null,
  "license": "all-rights-reserved",
  "original_content_size": 9719794,
  "original_format": "mp3",
  "playback_count": 3900360,
  "purchase_title": null,
  "purchase_url": null,
  "release": "",
  "release_day": null,
  "release_month": null,
  "release_year": null,
  "reposts_count": 10838,
  "state": "finished",
  "streamable": true,
  "tag_list": "Lorde Team Elephante Remix \"Progressive House\" electro glitch House \"Dance & EDM\" Dance",
  "track_type": null,
  "user": {
    "avatar_url": "https://i1.sndcdn.com/avatars-000247265130-hdtqg2-large.jpg",
    "id": 10915053,
    "kind": "user",
    "permalink_url": "http://soundcloud.com/iamtheelephante",
    "uri": "https://api.soundcloud.com/users/10915053",
    "username": "Elephante",
    "permalink": "iamtheelephante",
    "last_modified": "2017/03/06 16:03:33 +0000"
  },
  "likes_count": 52402,
  "attachments_uri": "https://api.soundcloud.com/tracks/134643370/attachments",
  "bpm": null,
  "key_signature": "",
  "user_favorite": false,
  "user_playback_count": null,
  "video_url": null,
  "download_url": null
}, {
  "id": 121542316,
  "kind": "track",
  "created_at": "2013/11/23 17:35:59 +0000",
  "last_modified": "2017/01/17 20:25:46 +0000",
  "permalink": "claptone-no-eyes-feat-jaw-1",
  "permalink_url": "https://soundcloud.com/gamperdadoni/claptone-no-eyes-feat-jaw-1",
  "title": "Claptone - No Eyes feat. Jaw (GAMPER & DADONI Remix)",
  "duration": 328050,
  "sharing": "public",
  "waveform_url": "https://w1.sndcdn.com/Crn1TlkYRp5r_m.png",
  "stream_url": "https://api.soundcloud.com/tracks/121542316/stream",
  "uri": "https://api.soundcloud.com/tracks/121542316",
  "user_id": 2928615,
  "artwork_url": "https://i1.sndcdn.com/artworks-000063526492-ko6j9z-large.jpg",
  "comment_count": 777,
  "commentable": true,
  "description": "Exclusively out on Alle Farben´s \"Winterheart Blue\" Sampler!\r\nhttps://itunes.apple.com/album/alle-farben-45-winterheart/id825611596\r\n\r\nGAMPER & DADONI:\r\nwww.facebook.com/gamperanddadoni\r\nCLAPTONE:\r\nhttps://www.facebook.com/claptone.official\r\n♪♫♪♫♪♫♪♫♪♫♪♫♪♫♪♫♪♫♪♫♪♫♪♫♪♫♪♫♪♫\r\nFEATURED ON YOUTUBE (Mr Suicide Sheep)\r\nhttp://youtu.be/_2-5gb75a0U\r\n\r\nTHANKS TO:\r\nPicture by Till van Loosen Photography\r\nhttps://www.facebook.com/tillvanloosenphotography",
  "download_count": 0,
  "downloadable": false,
  "embeddable_by": "all",
  "favoritings_count": 0,
  "genre": "Deep House",
  "isrc": "",
  "label_id": null,
  "label_name": "",
  "license": "cc-by-nc",
  "original_content_size": 13444121,
  "original_format": "mp3",
  "playback_count": 2758125,
  "purchase_title": "iTunes",
  "purchase_url": "https://itunes.apple.com/album/alle-farben-45-winterheart/id825611596",
  "release": "",
  "release_day": null,
  "release_month": null,
  "release_year": null,
  "reposts_count": 14825,
  "state": "finished",
  "streamable": true,
  "tag_list": "\"Gamper & Dadoni\" Claptone \"No Eyes\" Remix Edit Bootleg 2013 New Jaw 2014 Deep House Electronic",
  "track_type": "remix",
  "user": {
    "avatar_url": "https://i1.sndcdn.com/avatars-000216015189-76ijjj-large.jpg",
    "id": 2928615,
    "kind": "user",
    "permalink_url": "http://soundcloud.com/gamperdadoni",
    "uri": "https://api.soundcloud.com/users/2928615",
    "username": "GAMPER & DADONI",
    "permalink": "gamperdadoni",
    "last_modified": "2017/02/10 10:44:42 +0000"
  },
  "likes_count": 63184,
  "attachments_uri": "https://api.soundcloud.com/tracks/121542316/attachments",
  "bpm": null,
  "key_signature": "",
  "user_favorite": false,
  "user_playback_count": null,
  "video_url": null,
  "download_url": null
}, {
  "id": 274868969,
  "kind": "track",
  "created_at": "2016/07/22 15:04:40 +0000",
  "last_modified": "2017/03/26 15:03:54 +0000",
  "permalink": "don-diablo-steve-aoki-x-lush-simon-what-we-started-ft-bullysongs",
  "permalink_url": "https://soundcloud.com/hexagon/don-diablo-steve-aoki-x-lush-simon-what-we-started-ft-bullysongs",
  "title": "Don Diablo & Steve Aoki X Lush & Simon - What We Started ft. BullySongs",
  "duration": 203093,
  "sharing": "public",
  "waveform_url": "https://w1.sndcdn.com/2cLubCgMHKxP_m.png",
  "stream_url": "https://api.soundcloud.com/tracks/274868969/stream",
  "uri": "https://api.soundcloud.com/tracks/274868969",
  "user_id": 105504173,
  "artwork_url": "https://i1.sndcdn.com/artworks-000172832008-cahn86-large.jpg",
  "comment_count": 646,
  "commentable": true,
  "description": "\"What we started\" is dedicated to those of us who have the guts to follow their dreams and are willing to work hard for it. But...by now the song is also an anthem dedicated to every raver, dj and everyone else in the electronic music industry. It's incredible to see what we created together in such a short amount of time. We are part of a community that let's you escape your worries through music week after week, something which is much needed in dark times like these.\n\nFollow Don Diablo\nFacebook: www.facebook.com/officialdondiablo\nInstagram: www.instagram.com/dondiablo\nTwitter: www.twitter.com/dondiablo\n\nFollow Steve Aoki\nFacebook: www.facebook.com/steveaoki\nInstagram: www.instagram.com/steveaoki\nTwitter: www.twitter.com/steveaoki\n\nFollow Lush & Simon\nFacebook: www.facebook.com/lushandsimon\nInstagram: www.instagram.com/lushandsimon\nTwitter: www.twitter.com/lushandsimon\n\nFollow BullySongs\nFacebook: www.facebook.com/bullysongs\nInstagram: www.instagram.com/bullysongs \nTwitter: twitter.com/bullysongs\n\nFollow Hexagon\nFacebook: www.facebook.com/HexagonHQ\nInstagram: www.instagram.com/HexagonHQ\nTwitter: www.twitter.com/HexagonHQ",
  "download_count": 0,
  "downloadable": false,
  "embeddable_by": "all",
  "favoritings_count": 0,
  "genre": "Electronic",
  "isrc": null,
  "label_id": null,
  "label_name": "HEXAGON",
  "license": "all-rights-reserved",
  "original_content_size": 35810056,
  "original_format": "wav",
  "playback_count": 202756,
  "purchase_title": "Stream / Download",
  "purchase_url": "https://hexagon.lnk.to/WhatWeStarted",
  "release": "",
  "release_day": 22,
  "release_month": 7,
  "release_year": 2016,
  "reposts_count": 11747,
  "state": "finished",
  "streamable": true,
  "tag_list": "House Hexagon \"Don Diablo\" \"Steve Aoki\" \"Lush & Simon\" BullySongs",
  "track_type": null,
  "user": {
    "avatar_url": "https://i1.sndcdn.com/avatars-000245540234-ij34u5-large.jpg",
    "id": 105504173,
    "kind": "user",
    "permalink_url": "http://soundcloud.com/hexagon",
    "uri": "https://api.soundcloud.com/users/105504173",
    "username": "HEXAGON",
    "permalink": "hexagon",
    "last_modified": "2017/03/19 19:41:55 +0000"
  },
  "likes_count": 71623,
  "attachments_uri": "https://api.soundcloud.com/tracks/274868969/attachments",
  "bpm": null,
  "key_signature": "",
  "user_favorite": false,
  "user_playback_count": null,
  "video_url": null,
  "download_url": null
}]
